const palettes = [
  {
    family: '',
    primary: '',
    secondary: '',
    tertiary: '',
    accent: '',
    background: '',
  },
  {
    family: '',
    primary: '',
    secondary: '',
    tertiary: '',
    accent: '',
    background: '',
  },
  {
    family: '',
    primary: '',
    secondary: '',
    tertiary: '',
    accent: '',
    background: '',
  },
  {
    family: '',
    primary: '',
    secondary: '',
    tertiary: '',
    accent: '',
    background: '',
  },
  {
    family: '',
    primary: '',
    secondary: '',
    tertiary: '',
    accent: '',
    background: '',
  },
  {
    family: '',
    primary: '',
    secondary: '',
    tertiary: '',
    accent: '',
    background: '',
  },
  {
    family: '',
    primary: '',
    secondary: '',
    tertiary: '',
    accent: '',
    background: '',
  },
  {
    family: '',
    primary: '',
    secondary: '',
    tertiary: '',
    accent: '',
    background: '',
  },
  {
    family: '',
    primary: '',
    secondary: '',
    tertiary: '',
    accent: '',
    background: '',
  },
  {
    family: '',
    primary: '',
    secondary: '',
    tertiary: '',
    accent: '',
    background: '',
  },
];

export default palettes;